baseURL = "https://www.skycoin.net/blog"
languageCode = "en-us"
title = "Blog"
defaultContentLanguage = "en"

relativeURLs = true
canonifyURLs = true

googleAnalytics = "UA-105234182-1"
#disqusShortname = ""

# hugo-xmin specific variables
theme = "skycoin"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

# enables ```lang ``` style syntax highlighted blocks
pygmentsCodeFences = true
pygmentsStyle = "murphy"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "https://www.skycoin.net"
    weight = 1
[[menu.main]]
    name = "Blog"
    identifier = "blog"
    url = "/"
    weight = 2
[[menu.main]]
    name = "Explorer"
    identifier = "explorer"
    url = "https://explorer.skycoin.net"
    weight = 3
[[menu.main]]
    name = "Wallet"
    identifier = "wallet"
    url = "https://www.skycoin.net/downloads/"
    weight = 4
[[menu.main]]
    name = "Team"
    identifier = "team"
    url = "https://www.skycoin.net/team/"
    weight = 5
[[menu.main]]
    name = "Ecosystem"
    identifier = "ecosystem"
    url = "https://www.skycoin.net/ecosystem/"
    weight = 6        

[[menu.footer]]
  name = "skycoin.net"
  url = "https://www.skycoin.net/"
  weight = 1

[[menu.footer]]
  name = "Github"
  url = "https://github.com/skycoin"
  weight = 2

[[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/skycoinproject"
  weight = 3

[[menu.footer]]
  name = "Reddit"
  url = "https://reddit.com/r/SkycoinProject"
  weight = 4

[[menu.footer]]
  name = "Telegram"
  url = "https://t.me/Skycoin"
  weight = 5

[[menu.footer]]
  name = "Blockchain Explorer"
  url = "https://explorer.skycoin.net/"
  weight = 6

[author]
  name = "Skycoin"

[params]
  keywords = "skycoin"
  rss = "/index.xml"
  telegram = "https://t.me/Skycoin"
  description = "Skycoin Project Updates"
  email = ""
  github = "skycoin"
  twitter = "skycoinproject"
  twitterAnalytics = "ny03t"

[Languages]
[Languages.en]
  weight = -1
  title = "Blog"
  languageName = "English"

[Languages.zh]
  weight = 1
  title = "天空币博客"
  hasCJKLanguage = true
  languageName = "中文"

[Languages.ru]
  weight = 2
  title = "Блог"
  languageName = "Русский"

[Languages.ko]
  weight = 3
  title = "블로그"
  languageName = "한국어"

[Languages.es]
    weight = 4
    title = "Blog"
    languageName = "Español"

[Languages.de]
    weight = 5
    title = "Blog"
    languageName = "Deutsch"

[Languages.ja]
    weight = 6
    title = "Blog"
    languageName = "日本語"

[Languages.el]
    weight = 7
    title = "Blog"
    languageName = "Ελληνικά"

[Languages.fr]
    weight = 8
    title = "Blog"
    languageName = "Français"

[Languages.pt]
    weight = 9
    title = "Blog"
    languageName = "Português"

[Languages.it]
    weight = 10
    title = "Blog"
    languageName = "Italiano"

[[menu.languages]]
  name = "English"
  weight = -1
  url = "/"
[[menu.languages]]
  name = "中文"
  weight = 1
  url = "/zh/"
[[menu.languages]]
  name = "Русский"
  weight = 2
  url = "/ru/"
[[menu.languages]]
  name = "한국어"
  weight = 3
  url = "/ko/"
[[menu.languages]]
  name = "Español"
  weight = 4
  url = "/es/"
[[menu.languages]]
  name = "Deutsch"
  weight = 5
  url = "/de/"
[[menu.languages]]
  name = "日本語"
  weight = 6
  url = "/ja/"
[[menu.languages]]
  name = "Ελληνικά"
  weight = 7
  url = "/el/"
[[menu.languages]]
  name = "Français"
  weight = 8
  url = "/fr/"
[[menu.languages]]
  name = "Português"
  weight = 9
  url = "/pt/"
[[menu.languages]]
  name = "Italiano"
  weight = 10
  url = "/it/"
